'use client';

import Link from "next/link";
import { useEffect, useState } from "react";
import ImageUploader from "../components/ImageUploader";
import GamificationPanel from "../components/GamificationPanel";

export default function Home() {
  const [imageData, setImageData] = useState<string | null>(null);
  const [analysisCount, setAnalysisCount] = useState(0);

  useEffect(() => {
    const stored = Number(localStorage.getItem('analysisCount') || '0');
    setAnalysisCount(stored);
  }, []);

  const handleAnalysisComplete = () => {
    setAnalysisCount((prev) => {
      const next = prev + 1;
      localStorage.setItem('analysisCount', String(next));
      return next;
    });
  };

  return (
    <div className="flex min-h-screen flex-col">
      <nav className="flex flex-col items-center gap-2 bg-brand p-4 text-white sm:flex-row sm:justify-center sm:gap-6">
        <Link href="/how-it-works" className="hover:underline hover:text-gray-200 dark:hover:text-gray-300">
          How It Works
        </Link>
        <Link href="/faq" className="hover:underline hover:text-gray-200 dark:hover:text-gray-300">
          FAQ
        </Link>
        <Link href="/about" className="hover:underline hover:text-gray-200 dark:hover:text-gray-300">
          About
        </Link>
      </nav>
      <main className="flex flex-1 flex-col items-center justify-center p-4 text-center sm:p-8">
        <h1 className="heading text-4xl">Welcome to IsItAI</h1>
        <p className="text-lg text-gray-700 dark:text-gray-300">
          Determine whether an image was generated by artificial intelligence.
        </p>
        <div className="mt-6">
          <ImageUploader onFileSelect={setImageData} onAnalysisComplete={handleAnalysisComplete} />
          <GamificationPanel count={analysisCount} />
          {imageData && (
            <p className="mt-4 text-sm text-gray-700 dark:text-gray-300">Image selected.</p>
          )}
        </div>
      </main>
    </div>
  );
}

