'use client';

import Link from "next/link";
import { useEffect, useState } from "react";
import ImageUploader from "../components/ImageUploader";
import GamificationPanel from "../components/GamificationPanel";

export default function Home() {
  const [imageData, setImageData] = useState<string | null>(null);
  const [analysisCount, setAnalysisCount] = useState(0);

  useEffect(() => {
    const stored = Number(localStorage.getItem('analysisCount') || '0');
    setAnalysisCount(stored);
  }, []);

  const handleAnalysisComplete = () => {
    setAnalysisCount((prev) => {
      const next = prev + 1;
      localStorage.setItem('analysisCount', String(next));
      return next;
    });
  };

  return (
    <div className="flex min-h-screen flex-col">
      <nav className="flex flex-col items-center gap-2 bg-brand p-4 text-white sm:flex-row sm:justify-center sm:gap-6">
        <Link
          href="/how-it-works"
          className="rounded px-2 py-1 hover:underline hover:text-gray-200 focus-visible:outline-none focus-visible:underline focus-visible:ring-2 focus-visible:ring-white focus-visible:ring-offset-2 focus-visible:ring-offset-brand dark:hover:text-gray-300"
        >
          How It Works
        </Link>
        <Link
          href="/faq"
          className="rounded px-2 py-1 hover:underline hover:text-gray-200 focus-visible:outline-none focus-visible:underline focus-visible:ring-2 focus-visible:ring-white focus-visible:ring-offset-2 focus-visible:ring-offset-brand dark:hover:text-gray-300"
        >
          FAQ
        </Link>
        <Link
          href="/about"
          className="rounded px-2 py-1 hover:underline hover:text-gray-200 focus-visible:outline-none focus-visible:underline focus-visible:ring-2 focus-visible:ring-white focus-visible:ring-offset-2 focus-visible:ring-offset-brand dark:hover:text-gray-300"
        >
          About
        </Link>
      </nav>
      <main className="flex flex-1 items-center justify-center p-4 sm:p-8">
        <div className="grid w-full max-w-5xl grid-cols-1 gap-8 text-center sm:grid-cols-2 sm:text-left">
          <div>
            <h1 className="heading text-5xl sm:text-6xl">Welcome to IsItAI</h1>
            <p className="mt-4 text-xl sm:text-2xl text-gray-700 dark:text-gray-300">
              Determine whether an image was generated by artificial intelligence.
            </p>
          </div>
          <div className="mt-6 sm:mt-0">
            <ImageUploader onFileSelect={setImageData} onAnalysisComplete={handleAnalysisComplete} />
            <GamificationPanel count={analysisCount} />
            {imageData && (
              <p className="mt-4 text-sm text-gray-700 dark:text-gray-300">Image selected.</p>
            )}
          </div>
        </div>
      </main>
    </div>
  );
}

