import Link from "next/link";

export default function Home() {
  return (
    <div className="flex min-h-screen flex-col">
      <nav className="flex justify-center gap-6 bg-indigo-600 p-4 text-white">
        <Link href="/how-it-works" className="hover:underline">
          How It Works
        </Link>
        <Link href="/faq" className="hover:underline">
          FAQ
        </Link>
        <Link href="/about" className="hover:underline">
          About
        </Link>
      </nav>
      <main className="flex flex-1 flex-col items-center justify-center p-8 text-center">
        <h1 className="mb-4 text-4xl font-bold">Welcome to IsItAI</h1>
        <p className="text-lg text-gray-700">
          Determine whether an image was generated by artificial intelligence.
        </p>
      </main>
    </div>
  );
}
